name: myshop
description: A new Flutter project.

publish_to: 'none'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_lints: ^2.0

flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset:  assets/fonts/Lato-Regular.ttf
        - asset:  assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset:  assets/fonts/Anton-Regular.ttf
    


  

  
